name: Build and Deploy static content to Pages 🛠️

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'build'
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy 🚀
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} ✔️
        uses: actions/setup-node@v4
      - name: Build ✔️
        run: |
          npm run inst
          npm run page
      - name: Setup Pages ✔️
        uses: actions/configure-pages@v5
      - name: Upload artifact ✔️
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/'
      - name: Deploy to GitHub Pages ✔️
        id: deployment
        uses: actions/deploy-pages@v4
